//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotment
    {
        public int AllotmentId { get; set; }
        public string ConstructionJobNumber { get; set; }
        public string PEJobNumber { get; set; }
        public int JobStatusId { get; set; }
        public string JobSystem { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public string FundingInformation { get; set; }
        public string MinuteOrder { get; set; }
        public System.DateTime DatePosted { get; set; }
        public Nullable<byte> DistrictNumber { get; set; }
        public string Route { get; set; }
        public string Section { get; set; }
        public decimal BeginningBalance { get; set; }
        public decimal TotalBalance { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string Comments { get; set; }
    }
}
