//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel;

    public partial class ApplicationSecurity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationSecurity()
        {
            this.LegacySecurities = new HashSet<LegacySecurity>();
        }
        //[Key, Column(Order=0), ForeignKey("Application")]
        [DisplayName("Application")]
        public string ApplicationId { get; set; }
        //[Key, Column(Order = 1), ForeignKey("User")]
        [DisplayName("User")]
        public string UserId { get; set; }
        //[Key, Column(Order = 2), ForeignKey("Role")]
        [DisplayName("Role")]
        public string RoleId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegacySecurity> LegacySecurities { get; set; }
    }
}
