//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ArDOT_UserProvEntities1 : DbContext
    {
        public ArDOT_UserProvEntities1()
            : base("name=ArDOT_UserProvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ApplicationSecurity>()
                .HasKey(u => new { u.ApplicationId, u.UserId, u.RoleId }) ;

            //modelBuilder.Entity<ApplicationSecurity>()
            //    .Property(t => t.ApplicationId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);

            //modelBuilder.Entity<ApplicationSecurity>()
            //    .Property(t => t.UserId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);

            //modelBuilder.Entity<ApplicationSecurity>()
            //    .Property(t => t.RoleId).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);

            modelBuilder.Entity<LegacySecurity>()
                .HasKey(u => new { u.ApplicationId, u.UserId, u.RoleId, u.Sequence });
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationSecurity> ApplicationSecurities { get; set; }
        public virtual DbSet<HistoricalSecurity> HistoricalSecurities { get; set; }
        public virtual DbSet<LegacySecurity> LegacySecurities { get; set; }
        public virtual DbSet<PermissionResource> PermissionResources { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }

        public DbSet<ConsultantContractsInternal.ViewModels.UserRoleBudgetVM> UserRoleBudgetVMs { get; set; }
    }
}
