//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public Budget()
        {
            this.AppBudgets = new HashSet<AppBudget>();
            this.Applications = new HashSet<Application>();
            this.AppRequests = new HashSet<AppRequest>();
            this.Directories = new HashSet<Directory>();
            this.GrantedAccesses = new HashSet<GrantedAccess>();
        }
    
        public int BudgetId { get; set; }
        public string Budget1 { get; set; }
        public string Description { get; set; }
        public bool SpecialProject { get; set; }
        public Nullable<int> LocationId { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateEnabled { get; set; }
        public Nullable<System.DateTime> DateDisabled { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChangeUser { get; set; }
        public string OU { get; set; }
        public string HomeServerName { get; set; }
    
        public virtual ICollection<AppBudget> AppBudgets { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<AppRequest> AppRequests { get; set; }
        public virtual Location Location { get; set; }
        public virtual ICollection<Directory> Directories { get; set; }
        public virtual ICollection<GrantedAccess> GrantedAccesses { get; set; }
    }
}
