//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentsHistory
    {
        public int CommentId { get; set; }
        public string CommentNo { get; set; }
        public string Type { get; set; }
        public string Comment { get; set; }
        public string UserId { get; set; }
        public System.DateTime DateEntered { get; set; }
    }
}
