//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultantContractsEntities : DbContext
    {
        public ConsultantContractsEntities()
            : base("name=ConsultantContractsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Consultant> Consultants { get; set; }
        public virtual DbSet<ContractAllotment> ContractAllotments { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<ContractType> ContractTypes { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<SalaryRate> SalaryRates { get; set; }
        public virtual DbSet<SuppAgreement> SuppAgreements { get; set; }
        public virtual DbSet<SuppAllotment> SuppAllotments { get; set; }
        public virtual DbSet<SuppSalaryRate> SuppSalaryRates { get; set; }
        public virtual DbSet<WorkType> WorkTypes { get; set; }
        public virtual DbSet<ServiceRate> ServiceRates { get; set; }
        public virtual DbSet<SuppServiceRate> SuppServiceRates { get; set; }
        public virtual DbSet<AgreementType> AgreementTypes { get; set; }
        public virtual DbSet<SuppSubConsultantInfo> SuppSubConsultantInfoes { get; set; }
        public virtual DbSet<ContractSubConsultant> ContractSubConsultants { get; set; }
        public virtual DbSet<InvoicePayment> InvoicePayments { get; set; }
        public virtual DbSet<SubConsultantSalaryRate> SubConsultantSalaryRates { get; set; }
        public virtual DbSet<SubConsultantServiceRate> SubConsultantServiceRates { get; set; }
        public virtual DbSet<SuppSubConsultantSalaryRate> SuppSubConsultantSalaryRates { get; set; }
        public virtual DbSet<SuppSubConsultantServiceRate> SuppSubConsultantServiceRates { get; set; }
        public virtual DbSet<ResponsibleDivision> ResponsibleDivisions { get; set; }
        public virtual DbSet<CommentsHistory> CommentsHistories { get; set; }
        public virtual DbSet<InvoiceApproval> InvoiceApproval { get; set; }
        public virtual DbSet<USStates> USStates { get; set; }
        public virtual DbSet<CountryRegionNames> CountryRegionNames { get; set; }
    }
}
