//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public Directory()
        {
            this.AccessRequests = new HashSet<AccessRequest>();
            this.AppAdmins = new HashSet<AppAdmin>();
            this.Applications = new HashSet<Application>();
            this.Applications1 = new HashSet<Application>();
            this.AppRequests = new HashSet<AppRequest>();
            this.SecurityInstances = new HashSet<SecurityInstance>();
            this.Directory1 = new HashSet<Directory>();
            this.Messages = new HashSet<Message>();
            this.Messages1 = new HashSet<Message>();
            this.Messages2 = new HashSet<Message>();
            this.Messages3 = new HashSet<Message>();
            this.Messages4 = new HashSet<Message>();
        }
    
        public int DirectoryId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string EmployeeNumber { get; set; }
        public string UserId { get; set; }
        public string EmployeeStatus { get; set; }
        public string RecordType { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public string JobItemNo { get; set; }
        public string JobTitle { get; set; }
        public string WorkPhone { get; set; }
        public string WorkExtension { get; set; }
        public string EngineerNumber { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string DivisionDistrictIndicator { get; set; }
        public string CrewNumber { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
        public Nullable<int> ReportsToId { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<System.DateTime> DeleteFlagDate { get; set; }
        public Nullable<bool> TerminalServices { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> DateEnabled { get; set; }
        public Nullable<System.DateTime> DateDisabled { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChangeUser { get; set; }
    
        public virtual ICollection<AccessRequest> AccessRequests { get; set; }
        public virtual ICollection<AppAdmin> AppAdmins { get; set; }
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<Application> Applications1 { get; set; }
        public virtual ICollection<AppRequest> AppRequests { get; set; }
        public virtual Budget Budget { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<SecurityInstance> SecurityInstances { get; set; }
        public virtual ICollection<Directory> Directory1 { get; set; }
        public virtual Directory Directory2 { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<Message> Messages1 { get; set; }
        public virtual ICollection<Message> Messages2 { get; set; }
        public virtual ICollection<Message> Messages3 { get; set; }
        public virtual ICollection<Message> Messages4 { get; set; }
    }
}
