//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantedAccess
    {
        public int GrantedAccessId { get; set; }
        public int SecurityInstanceId { get; set; }
        public int AppId { get; set; }
        public int RoleId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> BudgetId { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Budget Budget { get; set; }
        public virtual Location Location { get; set; }
        public virtual Role Role { get; set; }
        public virtual SecurityInstance SecurityInstance { get; set; }
    }
}
