//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoricalSecurity
    {
        public string UserId { get; set; }
        public string ApplicationId { get; set; }
        public string RoleId { get; set; }
        public string PermissionId { get; set; }
        public string ResourceId { get; set; }
        public System.DateTime ChangeDateTime { get; set; }
        public string ChangeType { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Budget { get; set; }
        public string BudgetName { get; set; }
        public string Status { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationDesc { get; set; }
        public Nullable<System.DateTime> ApplicationStartEffectiveDate { get; set; }
        public Nullable<System.DateTime> ApplicationEndEffectiveDate { get; set; }
        public string RoleName { get; set; }
        public string RoleDesc { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDesc { get; set; }
        public string ResourceName { get; set; }
        public string ResourceDesc { get; set; }
        public string ChangeUserId { get; set; }
        public string ChangeUserFirstName { get; set; }
        public string ChangeUserLastName { get; set; }
    }
}
