//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvoicePayments = new HashSet<InvoicePayment>();
            this.InvoiceApproval = new HashSet<InvoiceApproval>();
        }
    
        public int ContractCode { get; set; }
        public int InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ConsultantInvoiceNo { get; set; }
        public Nullable<int> SubConsultantId { get; set; }
        public bool PrimeInvoice { get; set; }
        public Nullable<decimal> LumpSumPercentage { get; set; }
        public Nullable<decimal> T1SvcsCeiling { get; set; }
        public Nullable<decimal> T1FixedFeeMax { get; set; }
        public Nullable<decimal> T2SvcsCeiling { get; set; }
        public Nullable<decimal> T2FixedFeeMax { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string CountryCode { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public Nullable<decimal> ContractCeiling { get; set; }
        public string PhysicalAddress { get; set; }
        public string EmailAddress { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<decimal> T1FixedFee { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRate { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMax { get; set; }
        public Nullable<decimal> FCCM { get; set; }
        public Nullable<decimal> FieldServiceOverheadRate { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMax { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> T1Svcs { get; set; }
        public Nullable<decimal> T2Svcs { get; set; }
        public Nullable<decimal> T2FixedFee { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RemarkLastEditDate { get; set; }
        public string RemarkLastEditUser { get; set; }
        public Nullable<System.DateTime> PrimeApproval { get; set; }
        public string PrimeApprovalBy { get; set; }
        public int InvoiceId { get; set; }
        public int RevisionNo { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public bool IsSimple { get; set; }
        public string ConsultantJobNo { get; set; }
    
        public virtual Consultant SubConsultant { get; set; }
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoicePayment> InvoicePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceApproval> InvoiceApproval { get; set; }
    }
}
