//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProgCon_AllotmentsEntities : DbContext
    {
        public ProgCon_AllotmentsEntities()
            : base("name=ProgCon_AllotmentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vw_ActiveJobAllotments> vw_ActiveJobAllotments { get; set; }
        public DbSet<Allotment> Allotments { get; set; }
    }
}
