//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDAP
    {
        public int row_id { get; set; }
        public string cn { get; set; }
        public string employee_number { get; set; }
        public string userid { get; set; }
        public string email { get; set; }
        public string user_status { get; set; }
        public string Budget { get; set; }
        public string Room { get; set; }
        public string Location { get; set; }
        public string manager { get; set; }
        public string ReportsToID { get; set; }
        public string adspath { get; set; }
        public string ReportsTo { get; set; }
    }
}
