//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.AppLocations = new HashSet<AppLocation>();
            this.AppRequests = new HashSet<AppRequest>();
            this.Budgets = new HashSet<Budget>();
            this.GrantedAccesses = new HashSet<GrantedAccess>();
        }
    
        public int LocationId { get; set; }
        public string ShortDescription { get; set; }
        public string Description { get; set; }
        public int LocationTypeId { get; set; }
        public string PAHRIndicator { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateEnabled { get; set; }
        public Nullable<System.DateTime> DateDisabled { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChangeUser { get; set; }
    
        public virtual ICollection<AppLocation> AppLocations { get; set; }
        public virtual ICollection<AppRequest> AppRequests { get; set; }
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<GrantedAccess> GrantedAccesses { get; set; }
        public virtual LocationType LocationType { get; set; }
    }
}
