//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.Directories = new HashSet<Directory>();
        }
    
        public int MessageId { get; set; }
        public System.Guid WorkflowId { get; set; }
        public int StartedById { get; set; }
        public System.DateTime MessageEntryDate { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<int> ResponseById { get; set; }
        public string Response { get; set; }
        public int TargetDirectoryId { get; set; }
        public int MessageTypeId { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> AppRequestId { get; set; }
        public Nullable<int> AccessRequestId { get; set; }
        public Nullable<System.DateTime> SendEmailBy { get; set; }
        public Nullable<bool> EmailSent { get; set; }
        public Nullable<int> PrimaryRecipientId { get; set; }
    
        public virtual AccessRequest AccessRequest { get; set; }
        public virtual AppRequest AppRequest { get; set; }
        public virtual Directory Directory { get; set; }
        public virtual Directory Directory1 { get; set; }
        public virtual Directory Directory2 { get; set; }
        public virtual Directory Directory3 { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual ICollection<Directory> Directories { get; set; }
    }
}
