//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequiredShareFolder
    {
        public int RequiredShareFoldersId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> AppRoleId { get; set; }
        public string UNCPath { get; set; }
        public bool ACLModify { get; set; }
        public bool ACLReadExecute { get; set; }
        public bool ACLList { get; set; }
        public bool ACLRead { get; set; }
        public bool ACLWrite { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Role Role { get; set; }
    }
}
