//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryDetail
    {
        public int ContractCode { get; set; }
        public int InvoiceNo { get; set; }
        public int ItemNo { get; set; }
        public decimal Amount_calc_ { get; set; }
        public string JobTitle { get; set; }
        public string Rate { get; set; }
        public string Hours { get; set; }
        public string RateMin { get; set; }
        public string RateMax { get; set; }
        public bool TitleI { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
    }
}
