//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityInstance
    {
        public SecurityInstance()
        {
            this.AccessRequests = new HashSet<AccessRequest>();
            this.GrantedAccesses = new HashSet<GrantedAccess>();
        }
    
        public int SecurityInstanceId { get; set; }
        public int DirectoryId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Suspended { get; set; }
    
        public virtual ICollection<AccessRequest> AccessRequests { get; set; }
        public virtual ICollection<GrantedAccess> GrantedAccesses { get; set; }
        public virtual Directory Directory { get; set; }
    }
}
