//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityType
    {
        public SecurityType()
        {
            this.Applications = new HashSet<Application>();
            this.RoleSecurityTypes = new HashSet<RoleSecurityType>();
        }
    
        public int SecurityTypeId { get; set; }
        public string ShortDescription { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime DateEnabled { get; set; }
        public Nullable<System.DateTime> DateDisabled { get; set; }
        public System.DateTime LastChangeDate { get; set; }
        public string LastChangeUser { get; set; }
    
        public virtual ICollection<Application> Applications { get; set; }
        public virtual ICollection<RoleSecurityType> RoleSecurityTypes { get; set; }
    }
}
