//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AHTD_UserProvEntities : DbContext
    {
        public AHTD_UserProvEntities()
            : base("name=AHTD_UserProvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessRequestAction> AccessRequestActions { get; set; }
        public DbSet<AccessRequest> AccessRequests { get; set; }
        public DbSet<AppAdmin> AppAdmins { get; set; }
        public DbSet<AppBudget> AppBudgets { get; set; }
        public DbSet<AppClaim> AppClaims { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<AppLocation> AppLocations { get; set; }
        public DbSet<AppPrerequisite> AppPrerequisites { get; set; }
        public DbSet<AppRequest> AppRequests { get; set; }
        public DbSet<Budget> Budgets { get; set; }
        public DbSet<Claim> Claims { get; set; }
        public DbSet<GrantedAccess> GrantedAccesses { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<LocationType> LocationTypes { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<RequiredShareFolder> RequiredShareFolders { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<RoleSecurityType> RoleSecurityTypes { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<SecurityInstance> SecurityInstances { get; set; }
        public DbSet<SecurityType> SecurityTypes { get; set; }
        public DbSet<SubWorkflow> SubWorkflows { get; set; }
        public DbSet<Directory> Directories { get; set; }
        public DbSet<LDAP> LDAPs { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageType> MessageTypes { get; set; }
        public DbSet<TerminalService> TerminalServices { get; set; }
        public DbSet<vw_AHTDDirectory_EmpUserID> vw_AHTDDirectory_EmpUserID { get; set; }
        public DbSet<vw_AccessRequestsForActiveUsers> vw_AccessRequestsForActiveUsers { get; set; }
        public DbSet<vw_GrantedAccess> vw_GrantedAccess { get; set; }
        public DbSet<vw_OutstandingMessages> vw_OutstandingMessages { get; set; }
        public DbSet<vw_PAHREmployees> vw_PAHREmployees { get; set; }
        public DbSet<vw_PAHREmployeesNotInAD> vw_PAHREmployeesNotInAD { get; set; }
        public DbSet<vw_SupervisorLookup> vw_SupervisorLookup { get; set; }
    }
}
