//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDOR_MASTER
    {
        public string FED_ID { get; set; }
        public decimal SEQ_NO { get; set; }
        public string EXEMPT_CODE { get; set; }
        public string VENDOR_NAME { get; set; }
        public string BUS_NAME { get; set; }
        public string ADDRESS_1 { get; set; }
        public string ADDRESS_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string PHONE_NO { get; set; }
        public string FAX_NO { get; set; }
        public string VENDOR_IND { get; set; }
        public Nullable<System.DateTime> ELIG_STATUS_DATE { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string FED_MINORITY { get; set; }
        public string STATE_MINORITY { get; set; }
        public string VENDOR_TYPE { get; set; }
        public string COMMENT { get; set; }
        public Nullable<System.DateTime> LAST_PAYMENT_DATE { get; set; }
        public Nullable<System.DateTime> LAST_DATE { get; set; }
        public string LAST_USERID { get; set; }
    }
}
