//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActiveJobAllotments
    {
        public string ConstructionJobNumber { get; set; }
        public string PEJobNumber { get; set; }
        public string JobStatus { get; set; }
        public string JobSystem { get; set; }
        public string JobName { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime DatePosted { get; set; }
        public string FederalAidProjectNumber { get; set; }
        public string FunctionNumber { get; set; }
        public System.DateTime FAPFuncIssueDate { get; set; }
        public double FederalPercent { get; set; }
        public double StatePercent { get; set; }
        public double StateAidPercent { get; set; }
        public double OtherPercent { get; set; }
        public decimal CurrentAmount { get; set; }
        public decimal TotalBalance { get; set; }
        public decimal LastAmount { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
