//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AHTDDirectory_EmpUserID
    {
        public string Record_Type { get; set; }
        public int DirectoryID { get; set; }
        public string Employee_Number { get; set; }
        public string UserID { get; set; }
        public string Name_Last { get; set; }
        public string Name_First { get; set; }
    }
}
