//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GrantedAccess
    {
        public int SecurityInstanceId { get; set; }
        public int AppId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> BudgetId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public int AppRequestId { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
    }
}
