//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PAHREmployees
    {
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NickName { get; set; }
        public string PhoneArea { get; set; }
        public string PhonePrefix { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExt { get; set; }
        public string Budget { get; set; }
        public string EngineerNumber { get; set; }
        public string CrewNumber { get; set; }
        public string SectionId { get; set; }
        public string DivisionDistrictIndicator { get; set; }
        public string JobTitle { get; set; }
        public string JobItemNumber { get; set; }
        public string RoomNumber { get; set; }
        public string Location { get; set; }
    }
}
