//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContractsInternal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_SupervisorLookup
    {
        public string EmployeeNumber { get; set; }
        public string Branch { get; set; }
        public string DivDist { get; set; }
        public string Subset { get; set; }
        public string SecRECrew { get; set; }
        public string SupervisoryCode { get; set; }
        public string SupervisorEmployeeNo { get; set; }
    }
}
