//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultant
    {
        public Consultant()
        {
            this.Contracts = new HashSet<Contract>();
            this.SubInvoices = new HashSet<Invoice>();
            this.SuppSubConsultantInfoes = new HashSet<SuppSubConsultantInfo>();
            this.Remitee = new HashSet<Contract>();
            this.SubConsultantInfoes = new HashSet<ContractSubConsultant>();
        }
    
        public int ConsultantId { get; set; }
        public string TaxId { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string Name { get; set; }
        public string PrimaryContactFirstName { get; set; }
        public string PrimaryContactLastName { get; set; }
        public string SecondaryContactFirstName { get; set; }
        public string SecondaryContactLastName { get; set; }
        public string PhysicalAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string CountryCode { get; set; }
        public string PostalCode { get; set; }
        public string EmailAddress { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMax { get; set; }
        public Nullable<decimal> FCCM { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMax { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public bool Inactive { get; set; }
        public bool CityOrCounty { get; set; }
        public string BusinessPhoneNumber { get; set; }
        public string ContactPhoneNumber { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
        public virtual ICollection<Invoice> SubInvoices { get; set; }
        public virtual ICollection<SuppSubConsultantInfo> SuppSubConsultantInfoes { get; set; }
        public virtual ICollection<Contract> Remitee { get; set; }
        public virtual ICollection<ContractSubConsultant> SubConsultantInfoes { get; set; }
    }
}
