//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ConsultantContractsEntities : DbContext
    {
        public ConsultantContractsEntities()
            : base("name=ConsultantContractsEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Consultant> Consultants { get; set; }
        public DbSet<ContractAllotment> ContractAllotments { get; set; }
        public DbSet<Contract> Contracts { get; set; }
        public DbSet<ContractType> ContractTypes { get; set; }
        public DbSet<Invoice> Invoices { get; set; }
        public DbSet<SalaryRate> SalaryRates { get; set; }
        public DbSet<SuppAgreement> SuppAgreements { get; set; }
        public DbSet<SuppAllotment> SuppAllotments { get; set; }
        public DbSet<SuppSalaryRate> SuppSalaryRates { get; set; }
        public DbSet<WorkType> WorkTypes { get; set; }
        public DbSet<ServiceRate> ServiceRates { get; set; }
        public DbSet<SuppServiceRate> SuppServiceRates { get; set; }
        public DbSet<AgreementType> AgreementTypes { get; set; }
        public DbSet<SuppSubConsultantInfo> SuppSubConsultantInfoes { get; set; }
        public DbSet<ContractSubConsultant> ContractSubConsultants { get; set; }
        public DbSet<InvoicePayment> InvoicePayments { get; set; }
        public DbSet<SubConsultantSalaryRate> SubConsultantSalaryRates { get; set; }
        public DbSet<SubConsultantServiceRate> SubConsultantServiceRates { get; set; }
        public DbSet<SuppSubConsultantSalaryRate> SuppSubConsultantSalaryRates { get; set; }
        public DbSet<SuppSubConsultantServiceRate> SuppSubConsultantServiceRates { get; set; }
        public DbSet<ResponsibleDivision> ResponsibleDivisions { get; set; }
        public DbSet<CommentsHistory> CommentsHistories { get; set; }
        public DbSet<InvoiceApproval> InvoiceApproval { get; set; }
        public DbSet<USStates> USStates { get; set; }
        public DbSet<CountryRegionNames> CountryRegionNames { get; set; }
    
        public virtual int usp_RejectInvoice(Nullable<int> invoiceId, string reason, string userId)
        {
            var invoiceIdParameter = invoiceId.HasValue ?
                new ObjectParameter("InvoiceId", invoiceId) :
                new ObjectParameter("InvoiceId", typeof(int));
    
            var reasonParameter = reason != null ?
                new ObjectParameter("Reason", reason) :
                new ObjectParameter("Reason", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_RejectInvoice", invoiceIdParameter, reasonParameter, userIdParameter);
        }
    }
}
