//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public Contract()
        {
            this.ContractAllotments = new HashSet<ContractAllotment>();
            this.Invoices = new HashSet<Invoice>();
            this.SalaryRates = new HashSet<SalaryRate>();
            this.SuppAgreements = new HashSet<SuppAgreement>();
            this.WorkTypes = new HashSet<WorkType>();
            this.ServiceRates = new HashSet<ServiceRate>();
            this.ContractSubConsultants = new HashSet<ContractSubConsultant>();
        }
    
        public string JobNo { get; set; }
        public int ContractCode { get; set; }
        public int ConsultantId { get; set; }
        public int ContractTypeId { get; set; }
        public int AgreementTypeId { get; set; }
        public string ContractStatus { get; set; }
        public Nullable<System.DateTime> AgreementDate { get; set; }
        public Nullable<System.DateTime> NoticeProceedDate { get; set; }
        public string ConsultantContractNo { get; set; }
        public Nullable<decimal> ContractCeiling { get; set; }
        public Nullable<System.DateTime> ScheduledCompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<decimal> T1SvcsCeiling { get; set; }
        public Nullable<decimal> T1SvcsCeilingOrig { get; set; }
        public Nullable<decimal> T1FixedFeeMax { get; set; }
        public Nullable<decimal> T1FixedFeeMaxOrig { get; set; }
        public Nullable<decimal> T2SvcsCeiling { get; set; }
        public Nullable<decimal> T2SvcsCeilingOrig { get; set; }
        public Nullable<decimal> T2FixedFeeMax { get; set; }
        public Nullable<decimal> T2FixedFeeMaxOrig { get; set; }
        public Nullable<decimal> ContractCeilingOrig { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMax { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMaxOrig { get; set; }
        public Nullable<decimal> FCCM { get; set; }
        public Nullable<decimal> FCCMOrig { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMax { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMaxOrig { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> MultiplierOrig { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RemarkLastEditDate { get; set; }
        public string RemarkLastEditUser { get; set; }
        public string TaskOrderNo { get; set; }
        public int ResponsibleDivisionId { get; set; }
        public Nullable<int> RemitTo { get; set; }
        public short TitlePhase { get; set; }
    
        public virtual Consultant Consultant { get; set; }
        public virtual ICollection<ContractAllotment> ContractAllotments { get; set; }
        public virtual ContractType ContractType { get; set; }
        public virtual ICollection<Invoice> Invoices { get; set; }
        public virtual ICollection<SalaryRate> SalaryRates { get; set; }
        public virtual ICollection<SuppAgreement> SuppAgreements { get; set; }
        public virtual ICollection<WorkType> WorkTypes { get; set; }
        public virtual ICollection<ServiceRate> ServiceRates { get; set; }
        public virtual AgreementType AgreementType { get; set; }
        public virtual ICollection<ContractSubConsultant> ContractSubConsultants { get; set; }
        public virtual Consultant RemitToCon { get; set; }
        public virtual ResponsibleDivision ResponsibleDivision { get; set; }
    }
}
