//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractAllotment
    {
        public int ContractCode { get; set; }
        public string Func { get; set; }
        public string FAP { get; set; }
        public Nullable<decimal> FundingPriority { get; set; }
        public decimal FedPct { get; set; }
        public decimal StatePct { get; set; }
        public decimal StateAidPct { get; set; }
        public decimal AllottedAmt { get; set; }
        public decimal AllottedAmtOrig { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public decimal OtherPct { get; set; }
    
        public virtual Contract Contract { get; set; }
    }
}
