//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractSubConsultant
    {
        public ContractSubConsultant()
        {
            this.SubConsultantSalaryRates = new HashSet<SubConsultantSalaryRate>();
            this.SubConsultantServiceRates = new HashSet<SubConsultantServiceRate>();
        }
    
        public int ContractCode { get; set; }
        public Nullable<decimal> ContractCeiling { get; set; }
        public Nullable<decimal> T1SvcsCeiling { get; set; }
        public Nullable<decimal> T1SvcsCeilingOrig { get; set; }
        public Nullable<decimal> T1FixedFeeMax { get; set; }
        public Nullable<decimal> T1FixedFeeMaxOrig { get; set; }
        public Nullable<decimal> T2SvcsCeiling { get; set; }
        public Nullable<decimal> T2SvcsCeilingOrig { get; set; }
        public Nullable<decimal> T2FixedFeeMax { get; set; }
        public Nullable<decimal> T2FixedFeeMaxOrig { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<decimal> ContractCeilingOrig { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMax { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMaxOrig { get; set; }
        public Nullable<decimal> FCCM { get; set; }
        public Nullable<decimal> FCCMOrig { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMax { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public Nullable<decimal> MultiplierOrig { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMaxOrig { get; set; }
        public int SubConsultantId { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Consultant SubConsultant { get; set; }
        public virtual ICollection<SubConsultantSalaryRate> SubConsultantSalaryRates { get; set; }
        public virtual ICollection<SubConsultantServiceRate> SubConsultantServiceRates { get; set; }
    }
}
