//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePayment
    {
        public string Func { get; set; }
        public string FAP { get; set; }
        public decimal Amount { get; set; }
        public int InvoiceId { get; set; }
        public string ObjectCode { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
