//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponsibleDivision
    {
        public ResponsibleDivision()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int DivisionId { get; set; }
        public string DivisionName { get; set; }
        public string ShortName { get; set; }
        public string Budget { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
