//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppAgreement
    {
        public SuppAgreement()
        {
            this.SuppAllotments = new HashSet<SuppAllotment>();
            this.SuppSalaryRates = new HashSet<SuppSalaryRate>();
            this.SuppServiceRates = new HashSet<SuppServiceRate>();
            this.SuppSubConsultantInfoes = new HashSet<SuppSubConsultantInfo>();
        }
    
        public int ContractCode { get; set; }
        public string SuppNo { get; set; }
        public Nullable<decimal> ContractCeiling { get; set; }
        public Nullable<decimal> T1SvcsCeiling { get; set; }
        public Nullable<decimal> T1FixedFeeMax { get; set; }
        public Nullable<decimal> T2SvcsCeiling { get; set; }
        public Nullable<decimal> T2FixedFeeMax { get; set; }
        public Nullable<System.DateTime> SuppAgreementDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public Nullable<decimal> HomeOfficeOverheadRateMax { get; set; }
        public Nullable<decimal> FCCM { get; set; }
        public Nullable<decimal> FieldServiceOverheadRateMax { get; set; }
        public Nullable<decimal> Multiplier { get; set; }
        public string RemarkLastEditUser { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RemarkLastEditDate { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual ICollection<SuppAllotment> SuppAllotments { get; set; }
        public virtual ICollection<SuppSalaryRate> SuppSalaryRates { get; set; }
        public virtual ICollection<SuppServiceRate> SuppServiceRates { get; set; }
        public virtual ICollection<SuppSubConsultantInfo> SuppSubConsultantInfoes { get; set; }
    }
}
