//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuppAllotment
    {
        public string SuppNo { get; set; }
        public string Func { get; set; }
        public string FAP { get; set; }
        public Nullable<decimal> AllottedAmt { get; set; }
        public System.DateTime LastUpdateDate { get; set; }
        public string LastUpdateUser { get; set; }
        public int ContractCode { get; set; }
    
        public virtual SuppAgreement SuppAgreement { get; set; }
    }
}
