//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultantContracts.Infrastructure.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkType
    {
        public WorkType()
        {
            this.Contracts = new HashSet<Contract>();
        }
    
        public int WorkTypeId { get; set; }
        public string WorkTypeName { get; set; }
    
        public virtual ICollection<Contract> Contracts { get; set; }
    }
}
