//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("HighwayPoliceModel", "ContactInfo_Roster_FK1", "Roster", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AHTD.Security.Web.Model.Roster), "ContactInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AHTD.Security.Web.Model.ContactInfo), true)]
[assembly: EdmRelationshipAttribute("HighwayPoliceModel", "rank_NewRoster_FK1", "Rank", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AHTD.Security.Web.Model.Rank), "Roster", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AHTD.Security.Web.Model.Roster), true)]

#endregion

namespace AHTD.Security.Web.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class HighwayPoliceEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new HighwayPoliceEntities object using the connection string found in the 'HighwayPoliceEntities' section of the application configuration file.
        /// </summary>
        public HighwayPoliceEntities() : base("name=HighwayPoliceEntities", "HighwayPoliceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HighwayPoliceEntities object.
        /// </summary>
        public HighwayPoliceEntities(string connectionString) : base(connectionString, "HighwayPoliceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new HighwayPoliceEntities object.
        /// </summary>
        public HighwayPoliceEntities(EntityConnection connection) : base(connection, "HighwayPoliceEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ContactInfo> ContactInfoes
        {
            get
            {
                if ((_ContactInfoes == null))
                {
                    _ContactInfoes = base.CreateObjectSet<ContactInfo>("ContactInfoes");
                }
                return _ContactInfoes;
            }
        }
        private ObjectSet<ContactInfo> _ContactInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Rank> Ranks
        {
            get
            {
                if ((_Ranks == null))
                {
                    _Ranks = base.CreateObjectSet<Rank>("Ranks");
                }
                return _Ranks;
            }
        }
        private ObjectSet<Rank> _Ranks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Roster> Rosters
        {
            get
            {
                if ((_Rosters == null))
                {
                    _Rosters = base.CreateObjectSet<Roster>("Rosters");
                }
                return _Rosters;
            }
        }
        private ObjectSet<Roster> _Rosters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ContactInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContactInfoes(ContactInfo contactInfo)
        {
            base.AddObject("ContactInfoes", contactInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ranks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRanks(Rank rank)
        {
            base.AddObject("Ranks", rank);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Rosters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRosters(Roster roster)
        {
            base.AddObject("Rosters", roster);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighwayPoliceModel", Name="ContactInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ContactInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ContactInfo object.
        /// </summary>
        /// <param name="contactInfoID">Initial value of the ContactInfoID property.</param>
        /// <param name="rosterID">Initial value of the RosterID property.</param>
        /// <param name="primary">Initial value of the Primary property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="lastUserID">Initial value of the LastUserID property.</param>
        /// <param name="lastUpdate">Initial value of the LastUpdate property.</param>
        public static ContactInfo CreateContactInfo(global::System.Int32 contactInfoID, global::System.Int32 rosterID, global::System.Boolean primary, global::System.Byte type, global::System.String number, global::System.String description, global::System.String lastUserID, global::System.DateTime lastUpdate)
        {
            ContactInfo contactInfo = new ContactInfo();
            contactInfo.ContactInfoID = contactInfoID;
            contactInfo.RosterID = rosterID;
            contactInfo.Primary = primary;
            contactInfo.Type = type;
            contactInfo.Number = number;
            contactInfo.Description = description;
            contactInfo.LastUserID = lastUserID;
            contactInfo.LastUpdate = lastUpdate;
            return contactInfo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ContactInfoID
        {
            get
            {
                return _ContactInfoID;
            }
            set
            {
                if (_ContactInfoID != value)
                {
                    OnContactInfoIDChanging(value);
                    ReportPropertyChanging("ContactInfoID");
                    _ContactInfoID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ContactInfoID");
                    OnContactInfoIDChanged();
                }
            }
        }
        private global::System.Int32 _ContactInfoID;
        partial void OnContactInfoIDChanging(global::System.Int32 value);
        partial void OnContactInfoIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RosterID
        {
            get
            {
                return _RosterID;
            }
            set
            {
                OnRosterIDChanging(value);
                ReportPropertyChanging("RosterID");
                _RosterID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RosterID");
                OnRosterIDChanged();
            }
        }
        private global::System.Int32 _RosterID;
        partial void OnRosterIDChanging(global::System.Int32 value);
        partial void OnRosterIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Primary
        {
            get
            {
                return _Primary;
            }
            set
            {
                OnPrimaryChanging(value);
                ReportPropertyChanging("Primary");
                _Primary = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Primary");
                OnPrimaryChanged();
            }
        }
        private global::System.Boolean _Primary;
        partial void OnPrimaryChanging(global::System.Boolean value);
        partial void OnPrimaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.Byte _Type;
        partial void OnTypeChanging(global::System.Byte value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.String _Number;
        partial void OnNumberChanging(global::System.String value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastUserID
        {
            get
            {
                return _LastUserID;
            }
            set
            {
                OnLastUserIDChanging(value);
                ReportPropertyChanging("LastUserID");
                _LastUserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastUserID");
                OnLastUserIDChanged();
            }
        }
        private global::System.String _LastUserID;
        partial void OnLastUserIDChanging(global::System.String value);
        partial void OnLastUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private global::System.DateTime _LastUpdate;
        partial void OnLastUpdateChanging(global::System.DateTime value);
        partial void OnLastUpdateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighwayPoliceModel", "ContactInfo_Roster_FK1", "Roster")]
        public Roster Roster
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roster>("HighwayPoliceModel.ContactInfo_Roster_FK1", "Roster").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roster>("HighwayPoliceModel.ContactInfo_Roster_FK1", "Roster").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Roster> RosterReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Roster>("HighwayPoliceModel.ContactInfo_Roster_FK1", "Roster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Roster>("HighwayPoliceModel.ContactInfo_Roster_FK1", "Roster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighwayPoliceModel", Name="Rank")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Rank : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Rank object.
        /// </summary>
        /// <param name="rankid">Initial value of the rankid property.</param>
        /// <param name="rankname">Initial value of the rankname property.</param>
        /// <param name="rankabbrev">Initial value of the rankabbrev property.</param>
        /// <param name="priority">Initial value of the priority property.</param>
        /// <param name="userid">Initial value of the userid property.</param>
        /// <param name="datetime">Initial value of the datetime property.</param>
        public static Rank CreateRank(global::System.Int32 rankid, global::System.String rankname, global::System.String rankabbrev, global::System.Byte priority, global::System.String userid, global::System.DateTime datetime)
        {
            Rank rank = new Rank();
            rank.rankid = rankid;
            rank.rankname = rankname;
            rank.rankabbrev = rankabbrev;
            rank.priority = priority;
            rank.userid = userid;
            rank.datetime = datetime;
            return rank;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rankid
        {
            get
            {
                return _rankid;
            }
            set
            {
                if (_rankid != value)
                {
                    OnrankidChanging(value);
                    ReportPropertyChanging("rankid");
                    _rankid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rankid");
                    OnrankidChanged();
                }
            }
        }
        private global::System.Int32 _rankid;
        partial void OnrankidChanging(global::System.Int32 value);
        partial void OnrankidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rankname
        {
            get
            {
                return _rankname;
            }
            set
            {
                OnranknameChanging(value);
                ReportPropertyChanging("rankname");
                _rankname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rankname");
                OnranknameChanged();
            }
        }
        private global::System.String _rankname;
        partial void OnranknameChanging(global::System.String value);
        partial void OnranknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String rankabbrev
        {
            get
            {
                return _rankabbrev;
            }
            set
            {
                OnrankabbrevChanging(value);
                ReportPropertyChanging("rankabbrev");
                _rankabbrev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("rankabbrev");
                OnrankabbrevChanged();
            }
        }
        private global::System.String _rankabbrev;
        partial void OnrankabbrevChanging(global::System.String value);
        partial void OnrankabbrevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte priority
        {
            get
            {
                return _priority;
            }
            set
            {
                OnpriorityChanging(value);
                ReportPropertyChanging("priority");
                _priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("priority");
                OnpriorityChanged();
            }
        }
        private global::System.Byte _priority;
        partial void OnpriorityChanging(global::System.Byte value);
        partial void OnpriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String userid
        {
            get
            {
                return _userid;
            }
            set
            {
                OnuseridChanging(value);
                ReportPropertyChanging("userid");
                _userid = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("userid");
                OnuseridChanged();
            }
        }
        private global::System.String _userid;
        partial void OnuseridChanging(global::System.String value);
        partial void OnuseridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime datetime
        {
            get
            {
                return _datetime;
            }
            set
            {
                OndatetimeChanging(value);
                ReportPropertyChanging("datetime");
                _datetime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("datetime");
                OndatetimeChanged();
            }
        }
        private global::System.DateTime _datetime;
        partial void OndatetimeChanging(global::System.DateTime value);
        partial void OndatetimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighwayPoliceModel", "rank_NewRoster_FK1", "Roster")]
        public EntityCollection<Roster> Rosters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Roster>("HighwayPoliceModel.rank_NewRoster_FK1", "Roster");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Roster>("HighwayPoliceModel.rank_NewRoster_FK1", "Roster", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="HighwayPoliceModel", Name="Roster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Roster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Roster object.
        /// </summary>
        /// <param name="rosterID">Initial value of the RosterID property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="lastUserID">Initial value of the LastUserID property.</param>
        /// <param name="lastUpdate">Initial value of the LastUpdate property.</param>
        public static Roster CreateRoster(global::System.Int32 rosterID, global::System.Boolean active, global::System.String lastUserID, global::System.DateTime lastUpdate)
        {
            Roster roster = new Roster();
            roster.RosterID = rosterID;
            roster.Active = active;
            roster.LastUserID = lastUserID;
            roster.LastUpdate = lastUpdate;
            return roster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RosterID
        {
            get
            {
                return _RosterID;
            }
            set
            {
                if (_RosterID != value)
                {
                    OnRosterIDChanging(value);
                    ReportPropertyChanging("RosterID");
                    _RosterID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RosterID");
                    OnRosterIDChanged();
                }
            }
        }
        private global::System.Int32 _RosterID;
        partial void OnRosterIDChanging(global::System.Int32 value);
        partial void OnRosterIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmployeeID
        {
            get
            {
                return _EmployeeID;
            }
            set
            {
                OnEmployeeIDChanging(value);
                ReportPropertyChanging("EmployeeID");
                _EmployeeID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmployeeID");
                OnEmployeeIDChanged();
            }
        }
        private global::System.String _EmployeeID;
        partial void OnEmployeeIDChanging(global::System.String value);
        partial void OnEmployeeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Category
        {
            get
            {
                return _Category;
            }
            set
            {
                OnCategoryChanging(value);
                ReportPropertyChanging("Category");
                _Category = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Category");
                OnCategoryChanged();
            }
        }
        private global::System.String _Category;
        partial void OnCategoryChanging(global::System.String value);
        partial void OnCategoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RankID
        {
            get
            {
                return _RankID;
            }
            set
            {
                OnRankIDChanging(value);
                ReportPropertyChanging("RankID");
                _RankID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RankID");
                OnRankIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RankID;
        partial void OnRankIDChanging(Nullable<global::System.Int32> value);
        partial void OnRankIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameLast
        {
            get
            {
                return _NameLast;
            }
            set
            {
                OnNameLastChanging(value);
                ReportPropertyChanging("NameLast");
                _NameLast = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameLast");
                OnNameLastChanged();
            }
        }
        private global::System.String _NameLast;
        partial void OnNameLastChanging(global::System.String value);
        partial void OnNameLastChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameFirst
        {
            get
            {
                return _NameFirst;
            }
            set
            {
                OnNameFirstChanging(value);
                ReportPropertyChanging("NameFirst");
                _NameFirst = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameFirst");
                OnNameFirstChanged();
            }
        }
        private global::System.String _NameFirst;
        partial void OnNameFirstChanging(global::System.String value);
        partial void OnNameFirstChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameMiddle
        {
            get
            {
                return _NameMiddle;
            }
            set
            {
                OnNameMiddleChanging(value);
                ReportPropertyChanging("NameMiddle");
                _NameMiddle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameMiddle");
                OnNameMiddleChanged();
            }
        }
        private global::System.String _NameMiddle;
        partial void OnNameMiddleChanging(global::System.String value);
        partial void OnNameMiddleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NameAKA
        {
            get
            {
                return _NameAKA;
            }
            set
            {
                OnNameAKAChanging(value);
                ReportPropertyChanging("NameAKA");
                _NameAKA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NameAKA");
                OnNameAKAChanged();
            }
        }
        private global::System.String _NameAKA;
        partial void OnNameAKAChanging(global::System.String value);
        partial void OnNameAKAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String District
        {
            get
            {
                return _District;
            }
            set
            {
                OnDistrictChanging(value);
                ReportPropertyChanging("District");
                _District = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("District");
                OnDistrictChanged();
            }
        }
        private global::System.String _District;
        partial void OnDistrictChanging(global::System.String value);
        partial void OnDistrictChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Unit
        {
            get
            {
                return _Unit;
            }
            set
            {
                OnUnitChanging(value);
                ReportPropertyChanging("Unit");
                _Unit = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Unit");
                OnUnitChanged();
            }
        }
        private global::System.String _Unit;
        partial void OnUnitChanging(global::System.String value);
        partial void OnUnitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WorkCounty
        {
            get
            {
                return _WorkCounty;
            }
            set
            {
                OnWorkCountyChanging(value);
                ReportPropertyChanging("WorkCounty");
                _WorkCounty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WorkCounty");
                OnWorkCountyChanged();
            }
        }
        private global::System.String _WorkCounty;
        partial void OnWorkCountyChanging(global::System.String value);
        partial void OnWorkCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PostalCode
        {
            get
            {
                return _PostalCode;
            }
            set
            {
                OnPostalCodeChanging(value);
                ReportPropertyChanging("PostalCode");
                _PostalCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PostalCode");
                OnPostalCodeChanged();
            }
        }
        private global::System.String _PostalCode;
        partial void OnPostalCodeChanging(global::System.String value);
        partial void OnPostalCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ManualID
        {
            get
            {
                return _ManualID;
            }
            set
            {
                OnManualIDChanging(value);
                ReportPropertyChanging("ManualID");
                _ManualID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ManualID");
                OnManualIDChanged();
            }
        }
        private global::System.String _ManualID;
        partial void OnManualIDChanging(global::System.String value);
        partial void OnManualIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PIN
        {
            get
            {
                return _PIN;
            }
            set
            {
                OnPINChanging(value);
                ReportPropertyChanging("PIN");
                _PIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PIN");
                OnPINChanged();
            }
        }
        private global::System.String _PIN;
        partial void OnPINChanging(global::System.String value);
        partial void OnPINChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ComputerName
        {
            get
            {
                return _ComputerName;
            }
            set
            {
                OnComputerNameChanging(value);
                ReportPropertyChanging("ComputerName");
                _ComputerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ComputerName");
                OnComputerNameChanged();
            }
        }
        private global::System.String _ComputerName;
        partial void OnComputerNameChanging(global::System.String value);
        partial void OnComputerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notes
        {
            get
            {
                return _Notes;
            }
            set
            {
                OnNotesChanging(value);
                ReportPropertyChanging("Notes");
                _Notes = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Notes");
                OnNotesChanged();
            }
        }
        private global::System.String _Notes;
        partial void OnNotesChanging(global::System.String value);
        partial void OnNotesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastUserID
        {
            get
            {
                return _LastUserID;
            }
            set
            {
                OnLastUserIDChanging(value);
                ReportPropertyChanging("LastUserID");
                _LastUserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastUserID");
                OnLastUserIDChanged();
            }
        }
        private global::System.String _LastUserID;
        partial void OnLastUserIDChanging(global::System.String value);
        partial void OnLastUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private global::System.DateTime _LastUpdate;
        partial void OnLastUpdateChanging(global::System.DateTime value);
        partial void OnLastUpdateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighwayPoliceModel", "ContactInfo_Roster_FK1", "ContactInfo")]
        public EntityCollection<ContactInfo> ContactInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ContactInfo>("HighwayPoliceModel.ContactInfo_Roster_FK1", "ContactInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ContactInfo>("HighwayPoliceModel.ContactInfo_Roster_FK1", "ContactInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("HighwayPoliceModel", "rank_NewRoster_FK1", "Rank")]
        public Rank Rank
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rank>("HighwayPoliceModel.rank_NewRoster_FK1", "Rank").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rank>("HighwayPoliceModel.rank_NewRoster_FK1", "Rank").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Rank> RankReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Rank>("HighwayPoliceModel.rank_NewRoster_FK1", "Rank");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Rank>("HighwayPoliceModel.rank_NewRoster_FK1", "Rank", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
