CREATE TABLE [dbo].[Contracts] (
    [JobNo]                           NCHAR (10)     NOT NULL,
    [ContractCode]                    INT            IDENTITY (1, 1) NOT NULL,
    [ConsultantId]                    INT            NOT NULL,
    [ContractTypeId]                  INT            NOT NULL,
    [ContractStatus]                  CHAR (1)       NOT NULL,
    [AgreementDate]                   DATE           NULL,
    [NoticeProceedDate]               DATE           NULL,
    [ConsultantContractNo]            NVARCHAR (50)  NULL,
    [TaskOrderNo]                     NVARCHAR (10)  NULL,
    [AgreementTypeId]                 INT            NOT NULL,
    [ResponsibleDivisionId]           INT            CONSTRAINT [DF_Contracts_ResponsibleDivisionId] DEFAULT ((0)) NOT NULL,
    [RemitTo]                         INT            NULL,
    [ContractCeiling]                 MONEY          NULL,
    [ContractCeilingOrig]             MONEY          NULL,
    [T1SvcsCeiling]                   MONEY          NULL,
    [T1SvcsCeilingOrig]               MONEY          NULL,
    [T1FixedFeeMax]                   MONEY          NULL,
    [T1FixedFeeMaxOrig]               MONEY          NULL,
    [HomeOfficeOverheadRateMax]       DECIMAL (7, 4) NULL,
    [HomeOfficeOverheadRateMaxOrig]   DECIMAL (7, 4) NULL,
    [FCCM]                            DECIMAL (7, 4) NULL,
    [FCCMOrig]                        DECIMAL (7, 4) NULL,
    [T2SvcsCeiling]                   MONEY          NULL,
    [T2SvcsCeilingOrig]               MONEY          NULL,
    [T2FixedFeeMax]                   MONEY          NULL,
    [T2FixedFeeMaxOrig]               MONEY          NULL,
    [FieldServiceOverheadRateMax]     DECIMAL (7, 4) NULL,
    [FieldServiceOverheadRateMaxOrig] DECIMAL (7, 4) NULL,
    [Multiplier]                      DECIMAL (4, 2) NULL,
    [MultiplierOrig]                  DECIMAL (4, 2) NULL,
    [ScheduledCompletionDate]         DATE           NULL,
    [CompletionDate]                  DATETIME2 (7)  NULL,
    [Remarks]                         NVARCHAR (MAX) NULL,
    [RemarkLastEditDate]              DATETIME2 (7)  NULL,
    [RemarkLastEditUser]              NCHAR (7)      NULL,
    [LastUpdateDate]                  DATETIME2 (7)  NOT NULL,
    [LastUpdateUser]                  NCHAR (7)      NOT NULL,
    [TitlePhase]                      SMALLINT       CONSTRAINT [DF_Contracts_TitlePhase] DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_Contracts] PRIMARY KEY CLUSTERED ([ContractCode] ASC),
    CONSTRAINT [FK_Contracts_AgreementType] FOREIGN KEY ([AgreementTypeId]) REFERENCES [dbo].[AgreementType] ([AgreementTypeId]),
    CONSTRAINT [FK_Contracts_Consultant] FOREIGN KEY ([ConsultantId]) REFERENCES [dbo].[Consultant] ([ConsultantId]),
    CONSTRAINT [FK_Contracts_ConsultantRemitTo] FOREIGN KEY ([RemitTo]) REFERENCES [dbo].[Consultant] ([ConsultantId]),
    CONSTRAINT [FK_Contracts_ContractTypes] FOREIGN KEY ([ContractTypeId]) REFERENCES [dbo].[ContractTypes] ([TypeId]),
    CONSTRAINT [FK_Contracts_ResponsibleDivision] FOREIGN KEY ([ResponsibleDivisionId]) REFERENCES [dbo].[ResponsibleDivision] ([DivisionId])
);



