//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAuthorization.Data.Dto.Response
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserSecurityDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class UserSecurityDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UserAuthorization.Data.Dto.Response.ApplicationDto ApplicationField;
        
        private UserAuthorization.Data.Dto.Response.PermissionDto[] PermissionsField;
        
        private UserAuthorization.Data.Dto.Response.ResourceDto[] ResourcesField;
        
        private UserAuthorization.Data.Dto.Response.RoleDto[] RolesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.ApplicationDto Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.PermissionDto[] Permissions
        {
            get
            {
                return this.PermissionsField;
            }
            set
            {
                this.PermissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.ResourceDto[] Resources
        {
            get
            {
                return this.ResourcesField;
            }
            set
            {
                this.ResourcesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.RoleDto[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class ApplicationDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string NameField;
        
        private UserAuthorization.Data.Dto.Response.RoleDto[] RolesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.RoleDto[] Roles
        {
            get
            {
                return this.RolesField;
            }
            set
            {
                this.RolesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class PermissionDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationIdField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private UserAuthorization.Data.Dto.Response.LegacySecurityDto[] LegacySecuritiesField;
        
        private string NameField;
        
        private UserAuthorization.Data.Dto.Response.PermissionResourceDto[] PermissionResourcesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.LegacySecurityDto[] LegacySecurities
        {
            get
            {
                return this.LegacySecuritiesField;
            }
            set
            {
                this.LegacySecuritiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.PermissionResourceDto[] PermissionResources
        {
            get
            {
                return this.PermissionResourcesField;
            }
            set
            {
                this.PermissionResourcesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResourceDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class ResourceDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationIdField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private UserAuthorization.Data.Dto.Response.LegacySecurityDto[] LegacySecuritiesField;
        
        private string NameField;
        
        private UserAuthorization.Data.Dto.Response.PermissionResourceDto[] PermissionResourcesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.LegacySecurityDto[] LegacySecurities
        {
            get
            {
                return this.LegacySecuritiesField;
            }
            set
            {
                this.LegacySecuritiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.PermissionResourceDto[] PermissionResources
        {
            get
            {
                return this.PermissionResourcesField;
            }
            set
            {
                this.PermissionResourcesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class RoleDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationIdField;
        
        private string DescriptionField;
        
        private string IdField;
        
        private string NameField;
        
        private UserAuthorization.Data.Dto.Response.RolePermissionDto[] RolePermissionsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.RolePermissionDto[] RolePermissions
        {
            get
            {
                return this.RolePermissionsField;
            }
            set
            {
                this.RolePermissionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolePermissionDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class RolePermissionDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private UserAuthorization.Data.Dto.Response.ApplicationDto ApplicationField;
        
        private string ApplicationIdField;
        
        private string PermissionIdField;
        
        private UserAuthorization.Data.Dto.Response.RoleDto RoleField;
        
        private string RoleIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.ApplicationDto Application
        {
            get
            {
                return this.ApplicationField;
            }
            set
            {
                this.ApplicationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PermissionId
        {
            get
            {
                return this.PermissionIdField;
            }
            set
            {
                this.PermissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.RoleDto Role
        {
            get
            {
                return this.RoleField;
            }
            set
            {
                this.RoleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LegacySecurityDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class LegacySecurityDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationIdField;
        
        private UserAuthorization.Data.Dto.Response.PermissionDto PermissionDtoField;
        
        private UserAuthorization.Data.Dto.Response.ResourceDto ResourceDtoField;
        
        private string RoleIdField;
        
        private int SequenceField;
        
        private string UserIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.PermissionDto PermissionDto
        {
            get
            {
                return this.PermissionDtoField;
            }
            set
            {
                this.PermissionDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.ResourceDto ResourceDto
        {
            get
            {
                return this.ResourceDtoField;
            }
            set
            {
                this.ResourceDtoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence
        {
            get
            {
                return this.SequenceField;
            }
            set
            {
                this.SequenceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermissionResourceDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class PermissionResourceDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApplicationIdField;
        
        private UserAuthorization.Data.Dto.Response.PermissionDto PermissionField;
        
        private string PermissionIdField;
        
        private UserAuthorization.Data.Dto.Response.ResourceDto ResourceField;
        
        private string ResourceIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId
        {
            get
            {
                return this.ApplicationIdField;
            }
            set
            {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.PermissionDto Permission
        {
            get
            {
                return this.PermissionField;
            }
            set
            {
                this.PermissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PermissionId
        {
            get
            {
                return this.PermissionIdField;
            }
            set
            {
                this.PermissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public UserAuthorization.Data.Dto.Response.ResourceDto Resource
        {
            get
            {
                return this.ResourceField;
            }
            set
            {
                this.ResourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResourceId
        {
            get
            {
                return this.ResourceIdField;
            }
            set
            {
                this.ResourceIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractRolePermissionDto", Namespace="http://schemas.datacontract.org/2004/07/UserAuthorization.Data.Dto.Response")]
    public partial class ContractRolePermissionDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ContractCodeField;
        
        private string PermissionIdField;
        
        private string RoleIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContractCode
        {
            get
            {
                return this.ContractCodeField;
            }
            set
            {
                this.ContractCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PermissionId
        {
            get
            {
                return this.PermissionIdField;
            }
            set
            {
                this.PermissionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUserAuthorizationService")]
public interface IUserAuthorizationService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthorizationService/GetUserSecurity", ReplyAction="http://tempuri.org/IUserAuthorizationService/GetUserSecurityResponse")]
    UserAuthorization.Data.Dto.Response.UserSecurityDto GetUserSecurity(string userName, string application);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthorizationService/GetUserSecurity", ReplyAction="http://tempuri.org/IUserAuthorizationService/GetUserSecurityResponse")]
    System.Threading.Tasks.Task<UserAuthorization.Data.Dto.Response.UserSecurityDto> GetUserSecurityAsync(string userName, string application);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthorizationService/GetLegacySecurityInfo", ReplyAction="http://tempuri.org/IUserAuthorizationService/GetLegacySecurityInfoResponse")]
    UserAuthorization.Data.Dto.Response.LegacySecurityDto[] GetLegacySecurityInfo(string userName, string application);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthorizationService/GetLegacySecurityInfo", ReplyAction="http://tempuri.org/IUserAuthorizationService/GetLegacySecurityInfoResponse")]
    System.Threading.Tasks.Task<UserAuthorization.Data.Dto.Response.LegacySecurityDto[]> GetLegacySecurityInfoAsync(string userName, string application);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthorizationService/GetAvailableContracts", ReplyAction="http://tempuri.org/IUserAuthorizationService/GetAvailableContractsResponse")]
    UserAuthorization.Data.Dto.Response.ContractRolePermissionDto[] GetAvailableContracts(string userName, string application);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserAuthorizationService/GetAvailableContracts", ReplyAction="http://tempuri.org/IUserAuthorizationService/GetAvailableContractsResponse")]
    System.Threading.Tasks.Task<UserAuthorization.Data.Dto.Response.ContractRolePermissionDto[]> GetAvailableContractsAsync(string userName, string application);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserAuthorizationServiceChannel : IUserAuthorizationService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserAuthorizationServiceClient : System.ServiceModel.ClientBase<IUserAuthorizationService>, IUserAuthorizationService
{
    
    public UserAuthorizationServiceClient()
    {
    }
    
    public UserAuthorizationServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserAuthorizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserAuthorizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserAuthorizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public UserAuthorization.Data.Dto.Response.UserSecurityDto GetUserSecurity(string userName, string application)
    {
        return base.Channel.GetUserSecurity(userName, application);
    }
    
    public System.Threading.Tasks.Task<UserAuthorization.Data.Dto.Response.UserSecurityDto> GetUserSecurityAsync(string userName, string application)
    {
        return base.Channel.GetUserSecurityAsync(userName, application);
    }
    
    public UserAuthorization.Data.Dto.Response.LegacySecurityDto[] GetLegacySecurityInfo(string userName, string application)
    {
        return base.Channel.GetLegacySecurityInfo(userName, application);
    }
    
    public System.Threading.Tasks.Task<UserAuthorization.Data.Dto.Response.LegacySecurityDto[]> GetLegacySecurityInfoAsync(string userName, string application)
    {
        return base.Channel.GetLegacySecurityInfoAsync(userName, application);
    }
    
    public UserAuthorization.Data.Dto.Response.ContractRolePermissionDto[] GetAvailableContracts(string userName, string application)
    {
        return base.Channel.GetAvailableContracts(userName, application);
    }
    
    public System.Threading.Tasks.Task<UserAuthorization.Data.Dto.Response.ContractRolePermissionDto[]> GetAvailableContractsAsync(string userName, string application)
    {
        return base.Channel.GetAvailableContractsAsync(userName, application);
    }
}
